version: '3'
services:
  app:
    image: nginx:latest
    container_name: "app"
    ports:
      - "8080:80"
    volumes:
      - ./src/html:/app
      - ${HOME}/usr/Dropbox/share/stock/market_cap_per_code:/app/market_cap_per_code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  node:
    image: node:lts-alpine3.12 # nodeのversionはチェックする必要がありそう
    container_name: node
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
